Added Lubluelu SL60D vacuum device yaml
make-all/tuya-local pull request #1334
Opened 2023-11-22 12:26 UTC by t34wrj

2023-11-22 13:23 UTC, make-all requested changes

2023-11-22 13:23 UTC, make-all commented on custom_components/tuya_local/devices/lublueblu_sl60d_vacuum.yaml
> +       unit: "%"
This line is not correctly indented.

2023-11-22 14:52 UTC, t34wrj commented
Sorry - I can't see where the misalignment is.

2023-11-22 15:02 UTC, t34wrj commented on custom_components/tuya_local/devices/lublueblu_sl60d_vacuum.yaml
> +       unit: "%"
Sorry - have amended the indentation.

2023-11-24 09:06 UTC, t34wrj reviewed
Have updated YAML

2023-11-25 14:07 UTC, make-all approved these changes

2023-11-25 14:11 UTC, merged