add
make-all/tuya-local pull request #769
Opened 2023-06-06 08:47 UTC by g470258

2023-06-06 10:17 UTC, g470258 commented
thermex_IF_50_V with quality of 80%. DPS: {"updated_at": 1686045567.5918133, "101": false, "102": 37, "104": 65, "105": "2", "106": 0}
I don't know where to define dp 106. Always with state 0 and never changes.

2023-06-09 07:31 UTC, g470258 commented
{"updated_at": 1686045567.5918133, "101": false, "102": 37, "104": 65, "105": "2", "106": 0}

2023-06-13 00:53 UTC, make-all requested changes
see comments above

2023-06-13 00:53 UTC, make-all commented on custom_components/tuya_local/devices/thermex_IF_50_V.yaml
> +              value: Economy
Based on the implementation of away_mode I just made, the revised mapping should be:
```
 mapping:
          - dps_val: false
            value: "off"
          - dps_val: true
            constraint: work_mode
            conditions:
              - dps_val: "1"
                value: performance
              - dps_val: "2"
                value: electric
                default: true
              - dps_val: "3"
                value: eco
              - dps_val: "4"
                value: away
```

2023-06-13 00:55 UTC, make-all commented on custom_components/tuya_local/translations/ru.json
I will probably make the tweaks to the device config myself today, so don't worry about separating them.
I just thought the translations could go in straight away, while the config was being worked on.

2023-06-13 07:10 UTC, merged

2023-06-13 07:13 UTC, g470258 commented on custom_components/tuya_local/devices/thermex_IF_50_V.yaml
> +              value: Economy
Didn't understand what to rename?
```  dps:
    - id: 101
      type: boolean
      name: operation_mode
      hidden: true
      mapping:
        - dps_val: false
          value: "off"
    - id: 105
      type: string
      name: work_mode
      mapping:
          - dps_val: false
            value: "off"
          - dps_val: true
            constraint: work_mode
            conditions:
              - dps_val: "1"
                value: performance
              - dps_val: "2"
                value: electric
                default: true
              - dps_val: "3"
                value: eco
              - dps_val: "4"
                value: away       
```